<?xml version="1.0"?>
<package format="3">
  <name>set_pose_interface</name>
  <version>0.0.1</version>
  <description>Service definition for setting a pose in Gazebo</description>

  <maintainer email="robosub@example.com">Your Name</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>rosidl_default_generators</build_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>

  <!-- Dependency for gz_msgs -->
  <build_depend>geometry_msgs</build_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <member_of_group>rosidl_interface_packages</member_of_group>

</package>
