---
name: Publish a Docker image (AMD64; Common X86_64 Linux Machine)

# yamllint disable-line rule:truthy
on:
  push:
    tags: ["*"]
    branches:
      - ros2
      - dockertest

env:
  IMAGE_NAME: ${{ github.repository }}
  ROS_DISTRO: jazzy
  BRANCH: ${{ github.ref_name }}

jobs:
  build-and-push-to-docker-hub:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ioeslab/dave
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: .docker/jazzy.amd64.dockerfile
          build-args: |
            ROS_DISTRO=${{ env.ROS_DISTRO }}
            BRANCH=${{ env.BRANCH }}

      - name: Debug environment variables
        run: |
          echo "ROS_DISTRO: ${ROS_DISTRO}"
          echo "BRANCH: ${BRANCH}"
